# ラベルを作成する

## イメージ
+ 市場が始まる直前までに得られるデータを用いる
+ そのデータを用いて，1週間の価格変動を予測する
  →n日後(n=1,2,3,4,5,6,7)について学習させる
  + i日目の指標から，i+n日目の値を学習する
  1. データを読み込む
  2. 

## 使うモジュール
+ numpy

In [4]:
import numpy as np

1. モデルを作成
    + i日の指標を一まとめにした行ベクトルからなる配列を作る

In [5]:
diff_1 = np.load('diff_0day.npy')
_shape = diff_1.shape
x = np.zeros((_shape[0], _shape[1] * 10), dtype=float)
for id in range(10):
    x[:, id * _shape[1]: (id+1) * _shape[1]] = np.load('diff_' + str(id) + 'day.npy')
    
print(x.shape)

(1157, 150)


2. i日のデータに対する解答を作る
    + 用意したデータは(i)日と(i-n)日の差分を取ったデータになっている
    + 回答は，(i+n)日の値があればよい
    + とりあえずは，始値同士で比較する

In [6]:
y = np.zeros((_shape[0]-9, 10), dtype = float)
for i in range(_shape[0]-9):
    for n in range(10):
        y[i, n] = x[i+n,n * 15]

In [7]:
np.save('x.npy', x[9:_shape[0],:])
np.save('y.npy', y)
print(x[9:_shape[0],:].shape)
print(y.shape)
print(y)

(1148, 150)
(1148, 10)
[[  89.  139.  -43. ... -153. -331.    0.]
 [  50. -132. -253. ... -420. -769.    0.]
 [-182. -303. -315. ... -819. -550.    0.]
 ...
 [  77.   53.    2. ...  339.  281.    0.]
 [ -24.  -75.  -54. ...  204.  273.    0.]
 [ -51.  -30.  -10. ...  297.  358.    0.]]


In [8]:
print(y.std(axis=0))

[102.76073414 143.84739806 175.30623188 202.35707873 223.22528557
 242.48804017 260.26838122 276.3245837  290.518787     0.        ]


In [9]:
np.savetxt('test.csv', x[0,:], delimiter=', ')